import { Metadata } from "next";
import { getSession } from "../login/actions/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "ADMIN - Puro Queijo",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession()

    if (!session) {
        redirect("/login")
    }

    return (
        <>
            <main>
                {children}
            </main>
        </>
    );
}