import { Metadata } from "next";

export const metadata: Metadata = {
    title: "ADMIN - Puro Queijo",
    description: "Generated by create next app",
  };

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main>{children}</main>
        </>
    );
}