import { Metadata } from "next";
import { getSession } from "../login/actions/auth";
import { redirect } from "next/navigation";
import { DashboardSidebar } from "@/components/sidebar"
import { DashboardNavbar } from "@/components/navbar"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"

export const metadata: Metadata = {
    title: "ADMIN - Puro Queijo",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession()

    if (!session) {
        redirect("/login")
    }

    return (
        <SidebarProvider>
            <DashboardSidebar />
            <SidebarInset>
                <DashboardNavbar />
                <main className="flex-1 px-10">{children}</main>
            </SidebarInset>
        </SidebarProvider>
    );
}